#ArticleGetter downloads a JSON file from http://tools.wmflabs.org/catscan2/quick_intersection.php and extracts page ID, text ID and title.

require 'json'
require 'open-uri'

class ArticleGetter
  
  #sourceList: Array of URLs pointing to JSON files generated by http://tools.wmflabs.org/catscan2/quick_intersection.php 
  def initialize(sourceList)
    @sourceList = sourceList
  end
  
  #download the JSON file at the specified URL
  def result()
    result = []
    counter = 1
    @sourceList.each do |source|
      an_int = 1
      content = open(source, :content_length_proc => lambda{|content_length|
             bytes_total = content_length},
           :progress_proc => lambda{|bytes_transferred|
             print "\rDownloading JSON file #{counter}... %0.2f MB downloaded" % (bytes_transferred.to_f/1024.to_f/1024.to_f)
           }).read

      print "\nParsing...\n"

      pages = JSON.parse(content)["pages"]

      c = 0
      pages.each do |entry|
        newEntry = {}
        newEntry["page_id"] = entry["page_id"]
        newEntry["page_title"] = entry["page_title"]
        newEntry["text_id"] = entry["page_latest"]
        result << newEntry
        c+=1
        print "\rExtracting relevant data... #{c} of #{pages.count} entries extracted."
      end
      counter+=1
    end
    
    print "Done!\n"
    
    return result
    
  end
  
end